# Demo Data generator module for StudyPulse
js_demo_data_code = """
function getInitialDemoData() {
  return {
    goals: [
      {
        id: 'g-1',
        title: 'Master Data Structures & Algorithms',
        description: 'Comprehensive mastery of linear, non-linear, and dynamic programming algorithms for technical interviews and competitive programming.',
        type: 'Study',
        category: 'Academics',
        startDate: '2026-08-01',
        deadline: '2026-10-15',
        priority: 'High',
        status: 'In Progress',
        progress: 60,
        estimatedTime: 80,
        actualTime: 48,
        tags: ['dsa', 'leetcode', 'algorithms'],
        notes: 'Focus on time complexity analysis and optimal tree balancing.',
        subtasks: [
          { id: 'st-1', title: 'Array and String manipulation patterns', completed: true },
          { id: 'st-2', title: 'Linked lists and double pointer methods', completed: true },
          { id: 'st-3', title: 'Binary Trees and BST traversal', completed: true },
          { id: 'st-4', title: 'Graphs BFS, DFS and Dijkstra', completed: false },
          { id: 'st-5', title: 'Dynamic Programming state transitions', completed: false }
        ],
        important: true,
        pinned: true,
        created: '2026-08-01T10:00:00Z',
        updated: '2026-09-07T14:30:00Z'
      },
      {
        id: 'g-2',
        title: 'Complete Operating Systems Final Simulation',
        description: 'Build a multi-threaded virtual memory simulation and process scheduler prototype in C++.',
        type: 'Project',
        category: 'Project',
        startDate: '2026-08-15',
        deadline: '2026-09-25',
        priority: 'Critical',
        status: 'In Progress',
        progress: 45,
        estimatedTime: 50,
        actualTime: 22,
        tags: ['os', 'c++', 'threads', 'simulation'],
        notes: 'Dr. Desai requires complete concurrency test benchmarks.',
        subtasks: [
          { id: 'st-6', title: 'Design Process Control Block (PCB) structure', completed: true },
          { id: 'st-7', title: 'Implement Round Robin and Priority scheduling', completed: true },
          { id: 'st-8', title: 'Simulate Virtual Memory LRU page replacement', completed: false },
          { id: 'st-9', title: 'Draft final project report & performance graphs', completed: false }
        ],
        important: true,
        pinned: true,
        created: '2026-08-15T09:00:00Z',
        updated: '2026-09-08T08:15:00Z'
      },
      {
        id: 'g-3',
        title: 'Read 2 Research Papers on Distributed Systems',
        description: 'Analyze Google File System (GFS) and Raft Consensus protocol architecture papers.',
        type: 'Study',
        category: 'Research',
        startDate: '2026-09-01',
        deadline: '2026-09-30',
        priority: 'Medium',
        status: 'In Progress',
        progress: 50,
        estimatedTime: 15,
        actualTime: 7,
        tags: ['distributed', 'papers', 'raft'],
        notes: 'Write 1-page critique summarizing fault tolerance trade-offs.',
        subtasks: [
          { id: 'st-10', title: 'Read and annotate Raft consensus paper', completed: true },
          { id: 'st-11', title: 'Summarize leader election and log replication', completed: false }
        ],
        important: false,
        pinned: false,
        created: '2026-09-01T11:00:00Z',
        updated: '2026-09-05T16:00:00Z'
      },
      {
        id: 'g-4',
        title: 'Maintain 30-Day Coding Consistency Streak',
        description: 'Solve at least 2 algorithm problems and review core concepts every morning.',
        type: 'Personal',
        category: 'Habits',
        startDate: '2026-08-20',
        deadline: '2026-09-20',
        priority: 'Low',
        status: 'In Progress',
        progress: 75,
        estimatedTime: 30,
        actualTime: 23,
        tags: ['streak', 'habits', 'morning'],
        notes: 'Tracking on daily calendar and habit grid.',
        subtasks: [
          { id: 'st-12', title: 'Reach 10-day milestone', completed: true },
          { id: 'st-13', title: 'Reach 20-day milestone', completed: true },
          { id: 'st-14', title: 'Reach 30-day milestone', completed: false }
        ],
        important: false,
        pinned: false,
        created: '2026-08-20T08:00:00Z',
        updated: '2026-09-08T07:30:00Z'
      }
    ],
    tasks: [
      {
        id: 't-1',
        title: 'Implement Binary Search Tree balancing (AVL) in C++',
        category: 'Study',
        priority: 'High',
        dueDate: '2026-09-08',
        dueTime: '16:00',
        completed: false,
        tags: ['dsa', 'trees', 'assignment'],
        notes: 'Handle double rotations (Left-Right and Right-Left cases).',
        subtasks: [
          { id: 'tst-1', title: 'Implement balance factor calculation', completed: true },
          { id: 'tst-2', title: 'Implement single rotations', completed: false }
        ],
        recurring: 'none',
        order: 0,
        created: '2026-09-07T12:00:00Z'
      },
      {
        id: 't-2',
        title: 'Review Operating Systems Chapter 4 CPU Scheduling notes',
        category: 'Academics',
        priority: 'Medium',
        dueDate: '2026-09-08',
        dueTime: '19:30',
        completed: false,
        tags: ['os', 'revision', 'exam'],
        notes: 'Calculate Gantt charts for Multilevel Queue with Feedback.',
        subtasks: [],
        recurring: 'none',
        order: 1,
        created: '2026-09-07T15:00:00Z'
      },
      {
        id: 't-3',
        title: 'Submit Database Management Assignment 2 to Portal',
        category: 'Homework',
        priority: 'Critical',
        dueDate: '2026-09-09',
        dueTime: '23:59',
        completed: false,
        tags: ['dbms', 'sql', 'portal'],
        notes: 'PDF report must include B+ tree indexing benchmarks.',
        subtasks: [],
        recurring: 'none',
        order: 2,
        created: '2026-09-06T10:00:00Z'
      },
      {
        id: 't-4',
        title: 'Review Deadlocks Banker\\'s Algorithm Safety Checks',
        category: 'Study',
        priority: 'Low',
        dueDate: '2026-09-11',
        dueTime: '14:00',
        completed: true,
        tags: ['os', 'revision'],
        notes: 'Understood resource allocation graph cycle conditions.',
        subtasks: [],
        recurring: 'weekly',
        order: 3,
        created: '2026-09-05T09:00:00Z'
      }
    ],
    teachers: [
      {
        id: 'tech-1',
        name: 'Prof. Rahul Sharma',
        subject: 'Data Structures & Algorithms',
        phone: '+91 98765 43210',
        email: 'rsharma@university.edu',
        department: 'Computer Science & Engineering',
        room: 'CS-302 (Faculty Wing)',
        notes: 'Available for office hours on Tue & Thu 3:00 - 5:00 PM.'
      },
      {
        id: 'tech-2',
        name: 'Nivesh Kumar',
        subject: 'Operating Systems',
        phone: '+91 98123 45678',
        email: 'nkumar@university.edu',
        department: 'Computer Science & Engineering',
        room: 'CS-415 (Systems Lab)',
        notes: 'Guides OS projects and research in virtualization.'
      },
      {
        id: 'tech-3',
        name: 'Prof. Vikram Rao',
        subject: 'Database Management Systems',
        phone: '+91 98234 56789',
        email: 'vrao@university.edu',
        department: 'Information Technology',
        room: 'IT-204',
        notes: 'Queries about SQL project evaluation and query optimization.'
      }
    ],
    subjects: [
      {
        id: 'sub-1',
        name: 'Data Structures & Algorithms',
        code: 'CS201',
        teacherId: 'tech-1',
        teacherName: 'Prof. Rahul Sharma',
        teacherPhone: '+91 98765 43210',
        teacherEmail: 'rsharma@university.edu',
        description: 'Fundamental data structures, asymptotic analysis, sorting algorithms, trees, and graphs.',
        color: '#4f46e5',
        icon: 'code',
        semester: 'Semester 4',
        courseType: 'Core',
        cancelledClasses: 2,
        absentClasses: 1,
        attendanceRecords: [
          { id: 'att-1', date: '2026-09-02', day: 'Wednesday', status: 'cancelled', subjectId: 'sub-1', subjectName: 'Data Structures & Algorithms' },
          { id: 'att-2', date: '2026-09-07', day: 'Monday', status: 'cancelled', subjectId: 'sub-1', subjectName: 'Data Structures & Algorithms' },
          { id: 'att-3', date: '2026-09-04', day: 'Friday', status: 'absent', subjectId: 'sub-1', subjectName: 'Data Structures & Algorithms' }
        ],
        startDate: '2026-07-20',
        endDate: '2026-11-30',
        notes: 'Midterm exam accounts for 30%, Lab tests 20%, Finals 50%.',
        important: true,
        favorite: true
      },
      {
        id: 'sub-2',
        name: 'Operating Systems',
        code: 'CS204',
        teacherId: 'tech-2',
        teacherName: 'Nivesh Kumar',
        teacherPhone: '+91 98123 45678',
        teacherEmail: 'nkumar@university.edu',
        description: 'Process management, concurrency, deadlock prevention, virtual memory, and storage architectures.',
        color: '#0284c7',
        icon: 'cpu',
        semester: 'Semester 4',
        courseType: 'Core',
        cancelledClasses: 1,
        absentClasses: 0,
        attendanceRecords: [
          { id: 'att-4', date: '2026-09-04', day: 'Friday', status: 'cancelled', subjectId: 'sub-2', subjectName: 'Operating Systems' }
        ],
        startDate: '2026-07-20',
        endDate: '2026-11-30',
        notes: 'Textbook: Operating Systems: Three Easy Pieces (OSTEP).',
        important: true,
        favorite: true
      },
      {
        id: 'sub-3',
        name: 'Database Management Systems',
        code: 'CS208',
        teacherId: 'tech-3',
        teacherName: 'Prof. Vikram Rao',
        teacherPhone: '+91 98234 56789',
        teacherEmail: 'vrao@university.edu',
        description: 'Relational algebra, SQL, normalization up to BCNF, transaction management, and indexing.',
        color: '#059669',
        icon: 'database',
        semester: 'Semester 4',
        courseType: 'Core',
        cancelledClasses: 0,
        absentClasses: 2,
        attendanceRecords: [
          { id: 'att-5', date: '2026-08-28', day: 'Friday', status: 'absent', subjectId: 'sub-3', subjectName: 'Database Management Systems' },
          { id: 'att-6', date: '2026-09-03', day: 'Thursday', status: 'absent', subjectId: 'sub-3', subjectName: 'Database Management Systems' }
        ],
        startDate: '2026-07-20',
        endDate: '2026-11-30',
        notes: 'PostgreSQL lab exercises every Wednesday.',
        important: false,
        favorite: false
      }
    ],
    chapters: [
      // Subject 1: Data Structures
      {
        id: 'ch-1',
        subjectId: 'sub-1',
        chapterNumber: 1,
        name: 'Asymptotic Analysis & Arrays',
        description: 'Big O, Omega, Theta notations and dynamic array resizing.',
        status: 'Completed',
        progress: 100,
        startDate: '2026-07-22',
        targetDate: '2026-08-05',
        completionDate: '2026-08-04',
        estimatedStudyTime: 12,
        actualStudyTime: 14,
        notes: 'Mastered amortized analysis for ArrayList growth factor.',
        important: false,
        difficulty: 'Easy',
        resources: 'GeeksforGeeks, CLRS Chapter 1-3',
        relatedVideos: 'DSA Lecture 1'
      },
      {
        id: 'ch-2',
        subjectId: 'sub-1',
        chapterNumber: 2,
        name: 'Linked Lists & Pointer Logic',
        description: 'Singly, doubly, and circular linked lists with pointer reversals.',
        status: 'Completed',
        progress: 100,
        startDate: '2026-08-06',
        targetDate: '2026-08-18',
        completionDate: '2026-08-16',
        estimatedStudyTime: 14,
        actualStudyTime: 15,
        notes: 'Floyd cycle-finding algorithm tested and implemented.',
        important: true,
        difficulty: 'Medium',
        resources: 'LeetCode linked list card',
        relatedVideos: 'DSA Lecture 2'
      },
      {
        id: 'ch-3',
        subjectId: 'sub-1',
        chapterNumber: 3,
        name: 'Stacks, Queues & Monotonic Patterns',
        description: 'LIFO/FIFO implementations, monotonic stack applications, next greater element.',
        status: 'Completed',
        progress: 100,
        startDate: '2026-08-19',
        targetDate: '2026-08-30',
        completionDate: '2026-08-28',
        estimatedStudyTime: 16,
        actualStudyTime: 16,
        notes: 'Solved largest rectangle in histogram problem.',
        important: true,
        difficulty: 'Medium',
        resources: 'CLRS Stack & Queue chapter',
        relatedVideos: 'DSA Lecture 3'
      },
      {
        id: 'ch-4',
        subjectId: 'sub-1',
        chapterNumber: 4,
        name: 'Binary Trees, BST & AVL',
        description: 'Tree traversals (inorder, preorder, postorder, level), BST search/insert, AVL rotations.',
        status: 'In Progress',
        progress: 50,
        startDate: '2026-09-01',
        targetDate: '2026-09-18',
        completionDate: '',
        estimatedStudyTime: 20,
        actualStudyTime: 10,
        notes: 'Currently practicing AVL self-balancing rotations.',
        important: true,
        difficulty: 'Hard',
        resources: 'Visualgo Binary Tree animation',
        relatedVideos: 'DSA Lecture 5 — Binary Trees'
      },
      {
        id: 'ch-5',
        subjectId: 'sub-1',
        chapterNumber: 5,
        name: 'Graph Algorithms & Shortest Path',
        description: 'Adjacency list, BFS, DFS, Topological sort, Dijkstra, and Kruskal algorithms.',
        status: 'Not Started',
        progress: 0,
        startDate: '2026-09-19',
        targetDate: '2026-10-10',
        completionDate: '',
        estimatedStudyTime: 25,
        actualStudyTime: 0,
        notes: 'Scheduled for next month after tree mastery.',
        important: true,
        difficulty: 'Hard',
        resources: 'Algorithms by Sedgewick',
        relatedVideos: ''
      },

      // Subject 2: Operating Systems
      {
        id: 'ch-6',
        subjectId: 'sub-2',
        chapterNumber: 1,
        name: 'OS Architecture & System Calls',
        description: 'Kernel vs user mode, trap instructions, and POSIX system call interface.',
        status: 'Completed',
        progress: 100,
        startDate: '2026-07-22',
        targetDate: '2026-08-04',
        completionDate: '2026-08-03',
        estimatedStudyTime: 10,
        actualStudyTime: 9,
        notes: 'Trace system calls using strace in Linux.',
        important: false,
        difficulty: 'Easy',
        resources: 'OSTEP Chapters 1-3',
        relatedVideos: 'OS Chapter 1'
      },
      {
        id: 'ch-7',
        subjectId: 'sub-2',
        chapterNumber: 2,
        name: 'Processes, Fork & IPC',
        description: 'PCB structure, context switching, fork/exec/wait, pipes, and shared memory.',
        status: 'Completed',
        progress: 100,
        startDate: '2026-08-05',
        targetDate: '2026-08-20',
        completionDate: '2026-08-19',
        estimatedStudyTime: 15,
        actualStudyTime: 16,
        notes: 'Built process tree hierarchy demo in C.',
        important: true,
        difficulty: 'Medium',
        resources: 'OSTEP Chapters 4-6',
        relatedVideos: 'OS Chapter 2 — Process States'
      },
      {
        id: 'ch-8',
        subjectId: 'sub-2',
        chapterNumber: 3,
        name: 'Threads, Locks & Semaphores',
        description: 'POSIX pthreads, race conditions, critical section problem, mutex, and semaphores.',
        status: 'In Progress',
        progress: 60,
        startDate: '2026-08-21',
        targetDate: '2026-09-12',
        completionDate: '',
        estimatedStudyTime: 18,
        actualStudyTime: 11,
        notes: 'Solving Producer-Consumer and Readers-Writers synchronization problems.',
        important: true,
        difficulty: 'Hard',
        resources: 'The Little Book of Semaphores',
        relatedVideos: 'OS Concurrency playlist'
      },
      {
        id: 'ch-9',
        subjectId: 'sub-2',
        chapterNumber: 4,
        name: 'CPU Scheduling Algorithms',
        description: 'FCFS, SJF, SRTF, Round Robin, Priority, and Multi-level Feedback Queues.',
        status: 'Not Started',
        progress: 0,
        startDate: '2026-09-13',
        targetDate: '2026-09-24',
        completionDate: '',
        estimatedStudyTime: 14,
        actualStudyTime: 0,
        notes: 'Prepare Gantt chart calculations for mid-terms.',
        important: true,
        difficulty: 'Medium',
        resources: 'OSTEP Chapter 7-10',
        relatedVideos: 'OS Chapter 4 — CPU Scheduling'
      },
      {
        id: 'ch-10',
        subjectId: 'sub-2',
        chapterNumber: 5,
        name: 'Virtual Memory & Paging',
        description: 'Address translation, page tables, TLB cache, and page fault handling.',
        status: 'Not Started',
        progress: 0,
        startDate: '2026-09-25',
        targetDate: '2026-10-15',
        completionDate: '',
        estimatedStudyTime: 20,
        actualStudyTime: 0,
        notes: 'Crucial for OS project simulator.',
        important: true,
        difficulty: 'Hard',
        resources: 'OSTEP Paging section',
        relatedVideos: ''
      },
      {
        id: 'ch-11',
        subjectId: 'sub-2',
        chapterNumber: 6,
        name: 'Deadlocks & Prevention',
        description: 'Coffman conditions, Banker\\'s safety algorithm, deadlock detection and recovery.',
        status: 'Not Started',
        progress: 0,
        startDate: '2026-10-16',
        targetDate: '2026-10-30',
        completionDate: '',
        estimatedStudyTime: 12,
        actualStudyTime: 0,
        notes: 'Matrix allocation formulas.',
        important: false,
        difficulty: 'Medium',
        resources: 'Silberschatz chapter on Deadlocks',
        relatedVideos: ''
      },

      // Subject 3: DBMS
      {
        id: 'ch-12',
        subjectId: 'sub-3',
        chapterNumber: 1,
        name: 'Relational Model & SQL Fundamentals',
        description: 'Keys, schema constraints, joins, subqueries, group by, and views.',
        status: 'Completed',
        progress: 100,
        startDate: '2026-07-22',
        targetDate: '2026-08-10',
        completionDate: '2026-08-09',
        estimatedStudyTime: 12,
        actualStudyTime: 12,
        notes: 'Proficient in complex SQL window functions.',
        important: false,
        difficulty: 'Easy',
        resources: 'PostgreSQL official docs',
        relatedVideos: ''
      },
      {
        id: 'ch-13',
        subjectId: 'sub-3',
        chapterNumber: 2,
        name: 'Relational Algebra & Normalization',
        description: 'Functional dependencies, 1NF, 2NF, 3NF, and Boyce-Codd Normal Form (BCNF).',
        status: 'Completed',
        progress: 100,
        startDate: '2026-08-11',
        targetDate: '2026-08-28',
        completionDate: '2026-08-26',
        estimatedStudyTime: 15,
        actualStudyTime: 14,
        notes: 'Decomposition without lossy joins and dependency preservation.',
        important: true,
        difficulty: 'Medium',
        resources: 'Database System Concepts (Navathe)',
        relatedVideos: ''
      },
      {
        id: 'ch-14',
        subjectId: 'sub-3',
        chapterNumber: 3,
        name: 'Indexing & B+ Trees',
        description: 'Primary/secondary indices, B-Trees, B+ Tree node splitting, and query plans.',
        status: 'In Progress',
        progress: 30,
        startDate: '2026-08-29',
        targetDate: '2026-09-20',
        completionDate: '',
        estimatedStudyTime: 16,
        actualStudyTime: 6,
        notes: 'Working through B+ tree insertion rebalancing.',
        important: true,
        difficulty: 'Hard',
        resources: 'CMU 15-445 Database Systems',
        relatedVideos: ''
      },
      {
        id: 'ch-15',
        subjectId: 'sub-3',
        chapterNumber: 4,
        name: 'Transactions, ACID & Concurrency',
        description: 'Schedules, serializability, 2-phase locking (2PL), isolation levels, and write-ahead log.',
        status: 'Not Started',
        progress: 0,
        startDate: '2026-09-21',
        targetDate: '2026-10-10',
        completionDate: '',
        estimatedStudyTime: 18,
        actualStudyTime: 0,
        notes: 'Essential for backend system designs.',
        important: true,
        difficulty: 'Hard',
        resources: 'PostgreSQL MVCC documentation',
        relatedVideos: ''
      }
    ],
    timetableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    timetableSlots: [
      { id: 'ts-1', label: '09:00 - 10:00', start: '09:00', end: '10:00' },
      { id: 'ts-2', label: '10:00 - 11:00', start: '10:00', end: '11:00' },
      { id: 'ts-3', label: '11:15 - 12:15', start: '11:15', end: '12:15' },
      { id: 'ts-4', label: '12:15 - 01:15', start: '12:15', end: '13:15' },
      { id: 'ts-5', label: '02:00 - 03:00', start: '14:00', end: '15:00' },
      { id: 'ts-6', label: '03:00 - 04:00', start: '15:00', end: '16:00' }
    ],
    timetableClasses: [
      {
        id: 'tc-1',
        day: 'Monday',
        slotId: 'ts-1',
        subjectId: 'sub-1',
        subjectName: 'Data Structures & Algorithms',
        teacherName: 'Prof. Rahul Sharma',
        room: 'CS-Lab 1',
        color: '#4f46e5',
        important: true,
        notes: 'Bring laptop with C++ compiler ready.'
      },
      {
        id: 'tc-2',
        day: 'Monday',
        slotId: 'ts-2',
        subjectId: 'sub-2',
        subjectName: 'Operating Systems',
        teacherName: 'Nivesh Kumar',
        room: 'Lecture Hall 3',
        color: '#0284c7',
        important: false,
        notes: 'Discussion on thread concurrency primitives.'
      },
      {
        id: 'tc-3',
        day: 'Tuesday',
        slotId: 'ts-3',
        subjectId: 'sub-1',
        subjectName: 'DSA Tutorial & Problem Solving',
        teacherName: 'Prof. Rahul Sharma',
        room: 'CS-302',
        color: '#4f46e5',
        important: true,
        notes: 'Live coding on AVL tree rotations.'
      },
      {
        id: 'tc-4',
        day: 'Wednesday',
        slotId: 'ts-1',
        subjectId: 'sub-2',
        subjectName: 'OS Systems Lab',
        teacherName: 'Nivesh Kumar',
        room: 'Systems Lab B',
        color: '#0284c7',
        important: true,
        notes: 'POSIX semaphores coding verification.'
      },
      {
        id: 'tc-5',
        day: 'Thursday',
        slotId: 'ts-2',
        subjectId: 'sub-3',
        subjectName: 'Database Management Systems',
        teacherName: 'Prof. Vikram Rao',
        room: 'IT-Lab 2',
        color: '#059669',
        important: false,
        notes: 'B+ tree indexing query plans.'
      },
      {
        id: 'tc-6',
        day: 'Friday',
        slotId: 'ts-3',
        subjectId: 'sub-2',
        subjectName: 'Operating Systems',
        teacherName: 'Nivesh Kumar',
        room: 'Lecture Hall 3',
        color: '#0284c7',
        important: true,
        notes: 'Weekly summary and assignment review.'
      }
    ],
    stickyNotes: [
      {
        id: 'sn-1',
        title: 'OS Scheduling Formulas',
        content: 'Turnaround Time = Completion Time - Arrival Time\\nWaiting Time = Turnaround Time - Burst Time\\nResponse Time = First CPU Allocation - Arrival Time',
        color: 'yellow',
        priority: 'High',
        tags: ['os', 'formulae'],
        pinned: true,
        archived: false,
        created: '2026-09-04T10:00:00Z',
        updated: '2026-09-07T11:00:00Z'
      },
      {
        id: 'sn-2',
        title: 'Tree Traversal Reminders',
        content: 'Inorder (BST) -> Ascending sorted sequence\\nPreorder -> Root, Left, Right (useful for cloning tree)\\nPostorder -> Left, Right, Root (useful for deleting nodes / bottom-up DP)',
        color: 'cyan',
        priority: 'Medium',
        tags: ['dsa', 'trees'],
        pinned: true,
        archived: false,
        created: '2026-09-05T14:20:00Z',
        updated: '2026-09-07T14:30:00Z'
      },
      {
        id: 'sn-3',
        title: 'Prof. Sharma Recommended Readings',
        content: '1. OSTEP book chapters 7-9 on scheduler feedback\\n2. CSES Problem Set for Graph algorithms\\n3. CMU Database course lectures on storage engines',
        color: 'lavender',
        priority: 'Low',
        tags: ['books', 'reading'],
        pinned: false,
        archived: false,
        created: '2026-09-06T09:15:00Z',
        updated: '2026-09-06T09:15:00Z'
      },
      {
        id: 'sn-4',
        title: 'Project Submission Checklist',
        content: '✓ GitHub repo clean branch\\n✓ Readme with compile instructions\\n✓ Valgrind memory leak report zero errors\\n✓ Benchmarking charts PDF',
        color: 'coral',
        priority: 'High',
        tags: ['project', 'checklist'],
        pinned: false,
        archived: false,
        created: '2026-09-07T16:00:00Z',
        updated: '2026-09-08T09:00:00Z'
      }
    ],
    notes: [
      {
        id: 'n-1',
        title: 'Lecture Takeaways: CPU Scheduling Strategies',
        content: 'Multilevel Feedback Queue (MLFQ) solves both turnaround time and response time without knowing process burst times in advance.\\n\\nRule 1: If Priority(A) > Priority(B), A runs.\\nRule 2: If Priority(A) = Priority(B), A & B run in Round Robin using the time slice of that priority queue.\\nRule 3: When a job enters the system, it is placed at the top queue.\\nRule 4: Once a job uses up its time allotment at a given level, its priority is reduced.\\nRule 5: After some time period S, move all jobs in the system to the topmost queue (Starvation prevention).',
        subjectId: 'sub-2',
        chapterId: 'ch-9',
        category: 'Lecture Notes',
        tags: ['os', 'scheduling', 'mlfq'],
        pinned: true,
        favorite: true,
        date: '2026-09-06'
      },
      {
        id: 'n-2',
        title: 'Self-Balancing AVL Trees & Rotation Rules',
        content: 'An AVL tree is a self-balancing binary search tree where the difference between heights of left and right subtrees (Balance Factor) cannot be more than 1 for all nodes.\\n\\nBalance Factor = Height(Left) - Height(Right)\\n\\nCases for Rebalancing:\\n1. Left-Left (LL): Single right rotation on parent\\n2. Right-Right (RR): Single left rotation on parent\\n3. Left-Right (LR): Left rotation on child, then right rotation on parent\\n4. Right-Left (RL): Right rotation on child, then left rotation on parent',
        subjectId: 'sub-1',
        chapterId: 'ch-4',
        category: 'Study Summary',
        tags: ['dsa', 'trees', 'avl'],
        pinned: true,
        favorite: true,
        date: '2026-09-07'
      }
    ],
    playlists: [
      {
        id: 'pl-1',
        name: 'Data Structures Masterclass',
        description: 'Curated deep-dives into core algorithmic problem solving patterns and tree traversals.',
        color: '#4f46e5'
      },
      {
        id: 'pl-2',
        name: 'Operating Systems Full Course',
        description: 'Foundational lectures covering processes, threads, virtual memory, and kernels.',
        color: '#0284c7'
      }
    ],
    videos: [
      {
        id: 'vid-1',
        playlistId: 'pl-1',
        customTitle: 'DSA Lecture 1 — Introduction to Asymptotic Analysis',
        url: 'https://www.youtube.com/watch?v=8hly31xKli0',
        description: 'Complete breakdown of Big O notation, worst-case vs amortized analysis with array doubling.',
        subjectId: 'sub-1',
        chapterId: 'ch-1',
        duration: 48,
        progress: 100,
        completed: true,
        favorite: true,
        notes: 'Array growth factor of 2 amortizes appends to O(1).',
        tags: ['dsa', 'big-o']
      },
      {
        id: 'vid-2',
        playlistId: 'pl-1',
        customTitle: 'DSA Lecture 5 — Binary Trees & Traversal Strategies',
        url: 'https://www.youtube.com/watch?v=fAAZixBzIAI',
        description: 'Interactive recursion tree breakdown for Inorder, Preorder, Postorder and BFS level traversal.',
        subjectId: 'sub-1',
        chapterId: 'ch-4',
        duration: 62,
        progress: 45,
        completed: false,
        favorite: true,
        notes: 'Pause at 34:10 for recursive stack frame explanation.',
        tags: ['dsa', 'trees', 'recursion']
      },
      {
        id: 'vid-3',
        playlistId: 'pl-2',
        customTitle: 'OS Chapter 2 — Process States, Fork & PCB Structures',
        url: 'https://www.youtube.com/watch?v=26QPDBe-NB8',
        description: 'What happens under the hood when fork() is invoked and how the OS manages Process Control Blocks.',
        subjectId: 'sub-2',
        chapterId: 'ch-7',
        duration: 54,
        progress: 100,
        completed: true,
        favorite: false,
        notes: 'Fork returns 0 to child, child PID to parent.',
        tags: ['os', 'fork', 'processes']
      },
      {
        id: 'vid-4',
        playlistId: 'pl-2',
        customTitle: 'OS Chapter 4 — CPU Scheduling Algorithms Explained',
        url: 'https://www.youtube.com/watch?v=EWkQlLSeqew',
        description: 'Step by step Gantt charts for FCFS, SJF, and Round Robin quantum selection trade-offs.',
        subjectId: 'sub-2',
        chapterId: 'ch-9',
        duration: 42,
        progress: 25,
        completed: false,
        favorite: false,
        notes: 'If quantum is too small, context switch overhead dominates.',
        tags: ['os', 'scheduling']
      }
    ],
    habits: [
      {
        id: 'h-1',
        name: 'DSA Coding Practice (2 Problems)',
        category: 'Study',
        frequency: 'Daily',
        streak: 8,
        bestStreak: 15,
        completedToday: true,
        history: ['2026-09-01', '2026-09-02', '2026-09-03', '2026-09-04', '2026-09-05', '2026-09-06', '2026-09-07', '2026-09-08'],
        notes: 'Solve at least 1 Medium problem on trees or graphs every morning.'
      },
      {
        id: 'h-2',
        name: 'Review Class Lecture Notes (30 Mins)',
        category: 'Academics',
        frequency: 'Daily',
        streak: 5,
        bestStreak: 12,
        completedToday: false,
        history: ['2026-09-04', '2026-09-05', '2026-09-06', '2026-09-07'],
        notes: 'Review notes taken in OS and DBMS within 24 hours of lecture.'
      },
      {
        id: 'h-3',
        name: 'Daily 25-min Focused Study Sprint',
        category: 'Focus',
        frequency: 'Daily',
        streak: 12,
        bestStreak: 20,
        completedToday: true,
        history: ['2026-08-28', '2026-08-29', '2026-08-30', '2026-08-31', '2026-09-01', '2026-09-02', '2026-09-03', '2026-09-04', '2026-09-05', '2026-09-06', '2026-09-07', '2026-09-08'],
        notes: 'Phone off, full focus using Study Timer.'
      }
    ],
    calendarEvents: [
      {
        id: 'ce-1',
        title: 'OS Mid-Term Examination',
        type: 'Exam',
        date: '2026-09-18',
        time: '10:00',
        duration: '2 Hours',
        room: 'Examination Hall A',
        notes: 'Covers Chapters 1 to 4: Architecture, Processes, Threads, and Scheduling.'
      },
      {
        id: 'ce-2',
        title: 'DSA Trees Assignment 3 Due',
        type: 'Assignment',
        date: '2026-09-13',
        time: '23:59',
        duration: '',
        room: 'Online Portal',
        notes: 'C++ code submission with AVL rotation verification tests.'
      },
      {
        id: 'ce-3',
        title: 'Operating Systems Project Review Meeting',
        type: 'Event',
        date: '2026-09-22',
        time: '14:30',
        duration: '45 Mins',
        room: 'CS-415 (Systems Lab)',
        notes: 'Present scheduler prototype benchmarks to Nivesh Kumar.'
      },
      {
        id: 'ce-4',
        title: 'DBMS Group Project Checkpoint',
        type: 'Assignment',
        date: '2026-09-28',
        time: '17:00',
        duration: '1 Hour',
        room: 'IT-204',
        notes: 'Normalized schema up to BCNF and sample query load tests.'
      }
    ],
    studySessions: [
      {
        id: 'ss-1',
        subjectId: 'sub-1',
        subjectName: 'Data Structures & Algorithms',
        chapterName: 'Binary Trees & BST Traversal',
        duration: 45,
        mode: 'Pomodoro',
        timestamp: '2026-09-08T08:30:00Z',
        notes: 'Implemented recursive and iterative inorder traversals.'
      },
      {
        id: 'ss-2',
        subjectId: 'sub-2',
        subjectName: 'Operating Systems',
        chapterName: 'Threads, Locks & Semaphores',
        duration: 35,
        mode: 'Pomodoro',
        timestamp: '2026-09-07T18:00:00Z',
        notes: 'Solved producer-consumer buffer synchronization deadlock.'
      },
      {
        id: 'ss-3',
        subjectId: 'sub-1',
        subjectName: 'Data Structures & Algorithms',
        chapterName: 'Stacks & Monotonic Queue',
        duration: 50,
        mode: 'Stopwatch',
        timestamp: '2026-09-06T15:20:00Z',
        notes: 'Practiced sliding window maximum and next greater element.'
      }
    ],
    documents: [
      {
        id: 'doc-1',
        name: 'DSA_Comprehensive_Cheatsheet.pdf',
        title: 'Data Structures Complete Cheatsheet & Big-O Guide',
        subjectId: 'sub-1',
        category: 'Cheatsheet',
        size: '1.4 MB',
        type: 'application/pdf',
        uploadDate: '2026-09-04',
        content: 'Binary Search Trees, Heaps, AVL Trees, Hash Tables, and Graph traversal algorithms complexity breakdown.'
      },
      {
        id: 'doc-2',
        name: 'OS_Process_Scheduling_Manual.pdf',
        title: 'Operating Systems Process Scheduling & Concurrency Notes',
        subjectId: 'sub-2',
        category: 'Lecture Notes',
        size: '890 KB',
        type: 'application/pdf',
        uploadDate: '2026-09-02',
        content: 'Round Robin, Multilevel Queue, Banker\\'s Algorithm, and Virtual Memory Paging specifications.'
      },
      {
        id: 'doc-3',
        name: 'DBMS_Normalization_Assignment.docx',
        title: 'DBMS Assignment 2 - BCNF & 3NF Schema Decomposition',
        subjectId: 'sub-3',
        category: 'Assignment',
        size: '420 KB',
        type: 'application/msword',
        uploadDate: '2026-09-06',
        content: 'Functional dependencies, lossless join decomposition, and dependency preservation proofs.'
      }
    ],
    dailyNotes: {
      '2026-09-08': 'Productive morning! Completed AVL tree balancing logic and prepared for OS scheduling lecture. Need to revise Gantt charts tonight.'
    },
    activityLog: [
      { id: 'act-1', text: 'Completed study session: 45m on Data Structures & Algorithms', time: '2026-09-08T08:30:00Z' },
      { id: 'act-2', text: 'Checked off today\\'s habit: DSA Coding Practice (8-day streak 🔥)', time: '2026-09-08T08:00:00Z' },
      { id: 'act-3', text: 'Completed Chapter: Linked Lists & Pointer Logic in Data Structures', time: '2026-09-07T16:00:00Z' },
      { id: 'act-4', text: 'Updated Goal: Master Data Structures & Algorithms (60% complete)', time: '2026-09-07T14:30:00Z' },
      { id: 'act-5', text: 'Added class: OS Systems Lab to Wednesday 09:00 AM', time: '2026-09-06T11:00:00Z' }
    ],
    settings: {
      theme: 'light',
      accent: 'indigo',
      cardStyle: 'modern',
      density: 'comfortable',
      dashboardWidgets: {
        importantGoals: true,
        todos: true,
        subjects: true,
        currentChapters: true,
        timetable: true,
        stickyNotes: true,
        continueLearning: true,
        habits: true,
        statistics: true
      },
      widgetOrder: [
        'importantGoals',
        'todos',
        'subjects',
        'currentChapters',
        'timetable',
        'stickyNotes',
        'continueLearning',
        'habits',
        'statistics'
      ]
    }
  };
}
"""
